### ISSUE TITLE
Search result not displaying properly

### ISSUE THREAD

**Issue by RoonMoonlight** [j-fbriere/squawker#263]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.7.8+300014993

### Steps to reproduce the bug

1. Search any username or specific tags (e.g. @PixelsofMark or any hashtags)
2. The result shortly visible then returns "No results"

### Expected behavior

It should be able to display results normally

### Actual behavior

Returns No results instead of actual search results

### Screenshots/Screen recordings

![Screenshot_20240324_110033_Squawker](https://github.com/j-fbriere/squawker/assets/25527589/cc02ac53-8e28-40a4-981e-994a7b7dc8e2)

### Logs

N/A

### Affected Android/Custom ROM version

Android 14 / One UI 6

### Affected device model

Samsung Galaxy S22+

### Additional information

N/A

**Comment by j-fbriere** [comment]
Version [v3.8.1](https://github.com/j-fbriere/squawker/releases/tag/v3.8.1) should fix it.

**Comment by ryanthackston** [comment]
3.8.2

Android 13 / GrapheneOS Version: [2024050800](https://grapheneos.org/releases#2024050800)

Running on Pixel 4a.
Squawker was working up until yesterday. Now the feed doesnt work and the search doesn't work. However I can still pull up external twitter links in my app.

When searching usernames I get a TypeError which didnt happen before. I'm guessing it's a new twitter change on their end.
![Screenshot_20240517-113544](https://github.com/j-fbriere/squawker/assets/34466711/9be01213-dd7d-4665-802c-3aa9e9ba286c)

**Comment by j-fbriere** [comment]
@ryanthackston I just did you test and I get results.
Can you give me more info?
From your mobile, if you go to the Twitter/X site in a browser and you log with your same account, can you do the search with success?

**Comment by ryanthackston** [comment]
Yes it works for me on twitter page. I am currently logged on there with no problems
![Screenshot_20240517-122944](https://github.com/j-fbriere/squawker/assets/34466711/8f58a981-447f-42cd-9753-d0efa16c0b2f)

**Comment by ryanthackston** [comment]
Is there any more info I could give that's helpful?

Could it be that I have a Pixel 4a with GrapheneOS? I'm still getting updates on it.

How do you test on a Pixel 4a with GrapheneOS? Is there some kind of simulated OS testing software?

**Comment by autogris** [comment]
I'm experiencing the same error as the OP. Squawker 3.8.3, android 14, one ui 6.1. As soon as I scroll the results of tweet search they all disappear and get replaced with "No Results".
