### ISSUE TITLE
Force-bumped to top of comment thread

### ISSUE THREAD

**Issue by OkyDooky** [j-fbriere/squawker#391]
### Checklist

- [x] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [x] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.8.4+300018663

### Steps to reproduce the bug

1. Click on a post to see the comments
2. Scroll down
3. Once you go far enough down, you get bumped to the top.

### Expected behavior

When getting low enough to trigger the loading circle, it should only bump you up enough to align the bottom of the last post with the bottom of the app screen.

### Actual behavior

It seems it's when the "load more comments" flag gets triggered, it'll launch the view up to the top of the thread. Trying to hold the screen position with your finger doesn't seem to prevent it from happening.

### Affected Android/Custom ROM version

Android 15 / LineageOS 22.2

### Affected device model

Moto G7 Power (Ocean)

**Comment by j-fbriere** [comment]
Version v3.8.5 should fix this issue.

**Comment by poeticus** [comment]
Happening with me using v3.8.5 (F-Droid).
/e/os , Fairphone 3+

**Comment by j-fbriere** [comment]
> Happening with me using v3.8.5 (F-Droid).

I cannot reproduce unfortunately (I'm on Galaxy S21 Ultra / Android 15).

Can you provide a video to show me?

**Comment by I-Cant-Name-Things** [comment]
I'm still experiencing the issue as well. Link expires in two days

https://streamable.com/ep2jdl?src=player-page-share

**Comment by pamarcos** [comment]
Happening to me as well in GrapheneOS and 3.8.5

**Comment by adsarwal** [comment]
I have the same issue. 3.8.5
